import * as http from 'http';
import { URL } from 'url';

type Role = 'operator' | 'supervisor';
interface User { username: string; password: string; role: Role; }
interface Item { id: number; sku: string; name: string; stock: number; }
const users: User[] = [
  { username: 'operator', password: 'operator123', role: 'operator' },
  { username: 'supervisor', password: 'supervisor123', role: 'supervisor' },
];
const items: Item[] = [
  { id: 1, sku: 'FUL-001', name: 'Barcode Scanner', stock: 10 },
  { id: 2, sku: 'FUL-002', name: 'Shipping Label', stock: 100 },
];
const sessions = new Map<string, User>();
let nextOrder = 1;
function send(response: http.ServerResponse, status: number, data: unknown): void { response.writeHead(status, { 'Content-Type': 'application/json' }); response.end(JSON.stringify(data)); }
function read(request: http.IncomingMessage): Promise<Record<string, unknown>> { return new Promise((resolve, reject) => { let value = ''; request.on('data', (chunk) => { value += chunk; }); request.on('end', () => { try { resolve(value ? JSON.parse(value) : {}); } catch { reject(new Error('invalid json')); } }); request.on('error', reject); }); }
function user(request: http.IncomingMessage): User | undefined { return sessions.get(request.headers.authorization?.replace('Bearer ', '') || ''); }
function guard(request: http.IncomingMessage, response: http.ServerResponse, role?: Role): User | null { const current = user(request); if (!current) { send(response, 401, { error: 'authentication required' }); return null; } if (role && current.role !== role) { send(response, 403, { error: 'supervisor role required' }); return null; } return current; }
function page(): string { return `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width"><title>Fulfillment Console</title><style>body{font-family:Arial;max-width:760px;margin:2rem auto;padding:0 1rem}form{display:grid;gap:.6rem;max-width:380px}input,button{padding:.55rem;font:inherit}li{margin:.4rem 0}.ok{color:#064}.error{color:#a00}</style></head><body><main><h1>Fulfillment Console</h1><form id="login"><h2>Sign in</h2><label>Username <input name="username" value="operator"></label><label>Password <input name="password" type="password" value="operator123"></label><button>Sign in</button></form><section id="app" hidden><p id="user" role="status"></p><label for="search">Search inventory</label><input id="search" type="search"><ul id="items" aria-live="polite"></ul><h2>Create order</h2><form id="order"><label>Item <select name="itemId" id="item-select"></select></label><label>Quantity <input name="quantity" type="number" min="1" value="1"></label><button>Create order</button></form><p id="message" role="alert"></p></section></main><script>let token='';const $=s=>document.querySelector(s);async function load(){const r=await fetch('/api/items?q='+encodeURIComponent($('#search').value),{headers:{authorization:'Bearer '+token}});const d=await r.json();$('#items').innerHTML=d.items.map(i=>'<li>'+i.sku+' - '+i.name+' - stock: '+i.stock+'</li>').join('');$('#item-select').innerHTML=d.items.map(i=>'<option value="'+i.id+'">'+i.name+'</option>').join('');}$('#login').onsubmit=async e=>{e.preventDefault();const r=await fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});const d=await r.json();if(!r.ok){$('#message').textContent=d.error;return;}token=d.token;$('#login').hidden=true;$('#app').hidden=false;$('#user').textContent='Signed in as '+d.role;load();};$('#search').oninput=load;$('#order').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:JSON.stringify({itemId:Number(f.get('itemId')),quantity:Number(f.get('quantity'))})});const d=await r.json();$('#message').textContent=r.ok?'Order '+d.id+' created':d.error;$('#message').className=r.ok?'ok':'error';if(r.ok)load();};</script></body></html>`; }
const server = http.createServer(async (request, response) => { const url = new URL(request.url || '/', 'http://localhost'); try { if (url.pathname === '/' && request.method === 'GET') { response.writeHead(200, { 'Content-Type': 'text/html' }); response.end(page()); return; } if (url.pathname === '/api/login' && request.method === 'POST') { const input = await read(request); const found = users.find((candidate) => candidate.username === input.username && candidate.password === input.password); if (!found) { send(response, 401, { error: 'invalid credentials' }); return; } const token = `${found.username}-${Date.now()}-${Math.random()}`; sessions.set(token, found); send(response, 200, { token, role: found.role }); return; } if (url.pathname === '/api/items' && request.method === 'GET') { if (!guard(request, response)) return; const q = (url.searchParams.get('q') || '').toLowerCase(); send(response, 200, { items: items.filter((item) => `${item.sku} ${item.name}`.toLowerCase().includes(q)) }); return; } if (url.pathname === '/api/orders' && request.method === 'POST') { if (!guard(request, response)) return; const input = await read(request); const item = items.find((candidate) => candidate.id === Number(input.itemId)); const quantity = Number(input.quantity); if (!item || quantity < 1) { send(response, 400, { error: 'valid item and quantity are required' }); return; } if (item.stock < quantity) { send(response, 409, { error: 'insufficient stock' }); return; } item.stock -= quantity; send(response, 201, { id: `ORD-${nextOrder++}`, itemId: item.id, quantity }); return; } if (url.pathname === '/api/restock' && request.method === 'POST') { if (!guard(request, response, 'supervisor')) return; send(response, 200, { ok: true }); return; } } catch { send(response, 400, { error: 'bad request' }); return; } send(response, 404, { error: 'not found' }); });
server.listen(Number(process.env.PORT || 4273), '127.0.0.1', () => console.log('Complex challenge running on http://127.0.0.1:4273'));
