import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stg.gajab.com/');
  await page.locator('#home-bargain-guide-portal-overlay').click();
  await page.getByRole('link', { name: 'Log in / Sign up arrow' }).click();
  await page.getByRole('textbox', { name: 'Enter your Mobile Number here' }).click();
  await page.getByRole('textbox', { name: 'Enter your Mobile Number here' }).fill('7689543256');
  await page.getByRole('checkbox', { name: 'uncheck By continuing, you' }).check();
  await page.getByRole('button', { name: 'Request OTP' }).click();
  await page.locator('#otp-input-0').fill('1');
  await page.locator('#otp-input-1').fill('2');
  await page.locator('#otp-input-2').fill('3');
  await page.locator('#otp-input-3').fill('4');
  await page.locator('#otp-input-4').fill('5');
  await page.locator('#otp-input-5').fill('6');
  await page.getByText('Verify your Mobile NumberEnter OTP sent on 7689543256 Click to editDidn\'t').click();
  await page.getByRole('textbox', { name: 'Enter your Full Name here' }).click();
  await page.getByRole('textbox', { name: 'Enter your Full Name here' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your Full Name here' }).fill('A');
  await page.getByRole('textbox', { name: 'Enter your Full Name here' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your Full Name here' }).fill('Automation');
  await page.getByRole('dialog', { name: 'Let\'s quickly setup your' }).click();
  await page.getByRole('dialog', { name: 'Let\'s quickly setup your' }).check();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('link', { name: 'Kitchen tools Asking Price ₹376 ⚡️ 890 Times Bargained' }).click();
  await page.goto('https://stg.gajab.com/');
  await page.getByRole('link', { name: 'Kitchen tools Asking Price ₹227 ⚡️ 460 Times Bargained' }).click();
  await page.getByRole('button', { name: 'Show More arrow' }).click();
  await page.goto('https://stg.gajab.com/');
  await page.locator('body').press('ControlOrMeta+f');
  await page.locator('#home-live-orders-showcase-name-1788931250750').click();
  await page.locator('#home-wp1-view-more').click();
  await page.getByRole('link', { name: 'Toys Toys' }).click();
  await page.goto('https://stg.gajab.com/product-list/toys/19?offset=0&limit=48&orderBy=0');
  await page.getByRole('checkbox', { name: 'uncheck.svg SERA\'S BASKET' }).check();
  await page.goto('https://stg.gajab.com/product-list/toys/19?offset=0&limit=48&orderBy=0&brandIds=14');
  await page.locator('#price-filter-website-min-range-input').fill('427');
  await page.locator('#price-filter-website-max-range-input').fill('727');
  await page.getByRole('link', { name: 'Img_1787229933524.png Games' }).click();
  await page.getByRole('checkbox', { name: 'uncheck.svg SERA\'S BASKET' }).check();
  await page.goto('https://stg.gajab.com/product-list/games/18?offset=0&limit=48&orderBy=0&brandIds=14');
  await page.locator('#price-filter-website-min-range-input').fill('423');
  await page.locator('#price-filter-website-max-range-input').fill('733');
  await page.getByRole('link', { name: 'Img_1781183559370_2hf8bu8eul3' }).click();
  await page.locator('#pdp-button-7').click();
  await page.getByRole('slider', { name: 'Adjust offer amount' }).fill('0.9');
  await page.getByRole('button', { name: 'Offer Your Price' }).click();
  await page.locator('body').press('ControlOrMeta+-');
  await page.locator('body').press('ControlOrMeta+-');
  await page.getByRole('button', { name: 'Close bargain modal' }).click();
  await page.locator('#pdp-div-59').click();
  await page.getByRole('button', { name: 'Buy Now', exact: true }).click();
  await page.goto('https://stg.gajab.com/product-detail/classic-157-inch-soft-tip-dartboard-game-set-%7C-6-darts-included-%7C-premium-quality-round-target-board-for-kids-adults-%7C-indoor-family-fun-birthday-christmas-gift-multicolor-40-cm/202612786944');
  await page.locator('#pdp-div-59').click();
  await page.goto('https://stg.gajab.com/product-detail/classic-157-inch-soft-tip-dartboard-game-set-%7C-6-darts-included-%7C-premium-quality-round-target-board-for-kids-adults-%7C-indoor-family-fun-birthday-christmas-gift-multicolor-40-cm/202612786944');
  await page.getByText('⚡️ 8 bargains already').click();
  await page.getByRole('button', { name: 'Buy Now', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address line 1 *' }).click();
  await page.getByRole('textbox', { name: 'Address line 1 *' }).fill('brtrrwe');
  await page.getByRole('textbox', { name: 'Address Line 2 *' }).click();
  await page.getByRole('textbox', { name: 'Address Line 2 *' }).fill('tevat');
  await page.locator('#add-address-save-as-uncheck-home').click();
  await page.locator('#add-address-save-as-uncheck-home').check();
  await page.locator('#add-address-use-same-billing-uncheck').click();
  await page.locator('#add-address-use-same-billing-uncheck').check();
  await page.getByRole('img', { name: 'uncheck', exact: true }).click();
  await page.getByRole('img', { name: 'uncheck', exact: true }).check();
  await page.getByRole('button', { name: 'Save Address' }).click();
  await page.getByText('Pay Online₹670₹547Save 18%').click();
  await page.getByRole('button', { name: 'Pay ₹' }).click();
  await page.locator('iframe').contentFrame().getByRole('radio', { name: 'Netbanking BARB_R CNRB PUNB_R' }).check();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('iframe').contentFrame().getByTestId('netbanking').click();
  const page1 = await page1Promise;
  await page.locator('iframe').contentFrame().getByRole('button', { name: 'Canara Bank Canara Bank' }).first().click();
  await page1.getByRole('button', { name: 'Success' }).click();
  await page.locator('iframe').contentFrame().getByTestId('payment-status-heading').click();
  await page.goto('https://stg.gajab.com/order-confrim/GAJ2627001072');
  await page.locator('[id="success-1788931664103-0.08264373686456783"]').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('heading', { name: 'Order placed!' }).click();
  await expect(page.getByRole('heading', { name: 'Order placed!' })).toBeVisible();
  await page.getByRole('link', { name: 'My Bargains bargains' }).click();
  await expect(page.getByText('ASKING PRICE₹670BARGAIN PRICE₹')).toBeVisible();
  await page.getByText('You Saved ₹').click();
});