import axios from 'axios';
import * as dotenv from 'dotenv';
import { TestSummary, parsePlaywrightResults } from './send-email-report';

dotenv.config();

function getPassRateColor(passRate: number): string {
  if (passRate >= 90) return 'good';
  if (passRate >= 70) return 'warning';
  return 'attention';
}

function buildAdaptiveCard(summary: TestSummary): object {
  const passRate = summary.total > 0
    ? ((summary.passed / summary.total) * 100).toFixed(1)
    : '0';
  const passRateColor = getPassRateColor(Number(passRate));

  const testDetails = summary.tests.map(t => ({
    type: 'ColumnSet',
    columns: [
      {
        type: 'Column',
        width: 'stretch',
        items: [{ type: 'TextBlock', text: t.name, wrap: true, size: 'small' }],
      },
      {
        type: 'Column',
        width: 'auto',
        items: [{
          type: 'TextBlock',
          text: t.status.toUpperCase(),
          size: 'small',
          weight: 'bolder',
          color: t.status === 'pass' ? 'good' : t.status === 'fail' ? 'attention' : 'warning',
        }],
      },
    ],
  }));

  return {
    type: 'message',
    attachments: [
      {
        contentType: 'application/vnd.microsoft.card.adaptive',
        contentUrl: null,
        content: {
          $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
          type: 'AdaptiveCard',
          version: '1.4',
          body: [
            {
              type: 'Container',
              style: 'emphasis',
              items: [
                { type: 'TextBlock', text: 'Test Execution Report', size: 'large', weight: 'bolder' },
                { type: 'TextBlock', text: `${summary.teamName} | ${summary.timestamp}`, size: 'small', isSubtle: true },
              ],
            },
            {
              type: 'Container',
              items: [
                { type: 'TextBlock', text: `${passRate}%`, size: 'extraLarge', weight: 'bolder', color: passRateColor, horizontalAlignment: 'center' },
                { type: 'TextBlock', text: 'Pass Rate', horizontalAlignment: 'center', isSubtle: true, spacing: 'none' },
              ],
            },
            {
              type: 'ColumnSet',
              columns: [
                { type: 'Column', width: '1', items: [
                  { type: 'TextBlock', text: String(summary.total), size: 'extraLarge', weight: 'bolder', horizontalAlignment: 'center' },
                  { type: 'TextBlock', text: 'TOTAL', size: 'small', horizontalAlignment: 'center', isSubtle: true, spacing: 'none' },
                ]},
                { type: 'Column', width: '1', items: [
                  { type: 'TextBlock', text: String(summary.passed), size: 'extraLarge', weight: 'bolder', horizontalAlignment: 'center', color: 'good' },
                  { type: 'TextBlock', text: 'PASSED', size: 'small', horizontalAlignment: 'center', isSubtle: true, spacing: 'none' },
                ]},
                { type: 'Column', width: '1', items: [
                  { type: 'TextBlock', text: String(summary.failed), size: 'extraLarge', weight: 'bolder', horizontalAlignment: 'center', color: 'attention' },
                  { type: 'TextBlock', text: 'FAILED', size: 'small', horizontalAlignment: 'center', isSubtle: true, spacing: 'none' },
                ]},
                { type: 'Column', width: '1', items: [
                  { type: 'TextBlock', text: String(summary.skipped), size: 'extraLarge', weight: 'bolder', horizontalAlignment: 'center', color: 'warning' },
                  { type: 'TextBlock', text: 'SKIPPED', size: 'small', horizontalAlignment: 'center', isSubtle: true, spacing: 'none' },
                ]},
              ],
            },
            { type: 'TextBlock', text: 'Test Details', weight: 'bolder', separator: true },
            ...testDetails,
            {
              type: 'Container',
              style: 'emphasis',
              separator: true,
              items: [
                { type: 'TextBlock', text: `Generated by TestAutothon Automation Framework | Duration: ${summary.duration}`, size: 'small', isSubtle: true, horizontalAlignment: 'center' },
              ],
            },
          ],
        },
      },
    ],
  };
}

export async function sendTeamsReport(webhookUrl: string, summary: TestSummary): Promise<void> {
  const card = buildAdaptiveCard(summary);
  await axios.post(webhookUrl, card, {
    headers: { 'Content-Type': 'application/json' },
  });
  console.log('Report sent to Teams channel');
}

if (require.main === module) {
  const webhookUrl = process.env.TEAMS_WEBHOOK_URL;
  if (!webhookUrl) {
    console.log('Set TEAMS_WEBHOOK_URL in .env');
    process.exit(1);
  }

  const resultsFile = process.argv[2] || 'test-results.json';
  const summary = parsePlaywrightResults(resultsFile);
  sendTeamsReport(webhookUrl, summary).then(() => console.log('Done!'));
}
