import * as nodemailer from 'nodemailer';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

dotenv.config();

interface EmailConfig {
  host: string;
  port: number;
  secure: boolean;
  user: string;
  pass: string;
}

function getEmailConfig(): EmailConfig {
  return {
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: process.env.SMTP_SECURE === 'true',
    user: process.env.SMTP_USER || '',
    pass: process.env.SMTP_PASS || '',
  };
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  })[character] || character);
}

function buildHtmlReport(results: TestSummary): string {
  const passRate = results.total > 0
    ? ((results.passed / results.total) * 100).toFixed(1)
    : '0';

  const statusColor = Number(passRate) >= 90 ? '#27ae60' : Number(passRate) >= 70 ? '#f39c12' : '#e74c3c';

  return `
<!DOCTYPE html>
<html>
<head><style>
  body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
  .container { max-width: 700px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
  .header { background: #2c3e50; color: white; padding: 25px; text-align: center; }
  .header h1 { margin: 0; font-size: 22px; }
  .header p { margin: 5px 0 0; opacity: 0.8; }
  .summary { display: flex; justify-content: space-around; padding: 20px; background: #ecf0f1; }
  .stat { text-align: center; }
  .stat .number { font-size: 32px; font-weight: bold; }
  .stat .label { font-size: 12px; color: #7f8c8d; text-transform: uppercase; }
  .pass-rate { text-align: center; padding: 15px; }
  .pass-rate .rate { font-size: 48px; font-weight: bold; color: ${statusColor}; }
  .details { padding: 20px; }
  .test-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
  .pass { color: #27ae60; }
  .fail { color: #e74c3c; }
  .skip { color: #f39c12; }
  .footer { background: #34495e; color: white; padding: 15px; text-align: center; font-size: 12px; }
</style></head>
<body>
  <div class="container">
    <div class="header">
      <h1>Test Execution Report</h1>
      <p>${escapeHtml(results.teamName)} | ${escapeHtml(results.timestamp)}</p>
    </div>
    <div class="pass-rate">
      <div class="rate">${passRate}%</div>
      <div>Pass Rate</div>
    </div>
    <div class="summary">
      <div class="stat"><div class="number">${results.total}</div><div class="label">Total</div></div>
      <div class="stat"><div class="number pass">${results.passed}</div><div class="label">Passed</div></div>
      <div class="stat"><div class="number fail">${results.failed}</div><div class="label">Failed</div></div>
      <div class="stat"><div class="number skip">${results.skipped}</div><div class="label">Skipped</div></div>
    </div>
    <div class="details">
      <h3>Test Details</h3>
      ${results.tests.map(t => `
        <div class="test-row">
          <span>${escapeHtml(t.name)}</span>
          <span class="${t.status}">${t.status.toUpperCase()}</span>
        </div>
      `).join('')}
    </div>
    <div class="footer">
      <p>Generated by TestAutothon Automation Framework</p>
      <p>Duration: ${escapeHtml(results.duration)}</p>
    </div>
  </div>
</body>
</html>`;
}

export interface TestResult {
  name: string;
  status: 'pass' | 'fail' | 'skip';
  duration?: string;
  error?: string;
}

export interface TestSummary {
  teamName: string;
  timestamp: string;
  total: number;
  passed: number;
  failed: number;
  skipped: number;
  duration: string;
  tests: TestResult[];
}

export async function sendTestReport(
  recipients: string[],
  summary: TestSummary,
  attachments?: string[]
): Promise<void> {
  const config = getEmailConfig();

  const transporter = nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    auth: { user: config.user, pass: config.pass },
  });

  const htmlContent = buildHtmlReport(summary);
  const passRate = summary.total > 0
    ? ((summary.passed / summary.total) * 100).toFixed(1)
    : '0';

  const emailAttachments = (attachments || [])
    .filter(f => fs.existsSync(f))
    .map(f => ({ filename: path.basename(f), path: f }));

  await transporter.sendMail({
    from: `"${summary.teamName} Test Bot" <${config.user}>`,
    to: recipients.join(', '),
    subject: `Test Report: ${passRate}% Pass Rate | ${summary.total} Tests | ${summary.timestamp}`,
    html: htmlContent,
    attachments: emailAttachments,
  });

  console.log(`Report sent to: ${recipients.join(', ')}`);
}

export function parsePlaywrightResults(resultsPath: string): TestSummary {
  const raw = JSON.parse(fs.readFileSync(resultsPath, 'utf-8'));
  const tests: TestResult[] = [];

  for (const suite of raw.suites || []) {
    for (const spec of suite.specs || []) {
      tests.push({
        name: `${suite.title} > ${spec.title}`,
        status: spec.ok ? 'pass' : 'fail',
        duration: `${spec.tests?.[0]?.results?.[0]?.duration || 0}ms`,
      });
    }
  }

  return {
    teamName: process.env.TEAM_NAME || 'TestAutothon Team',
    timestamp: new Date().toISOString(),
    total: tests.length,
    passed: tests.filter(t => t.status === 'pass').length,
    failed: tests.filter(t => t.status === 'fail').length,
    skipped: tests.filter(t => t.status === 'skip').length,
    duration: `${(raw.stats?.duration || 0) / 1000}s`,
    tests,
  };
}

if (require.main === module) {
  const resultsFile = process.argv[2] || 'test-results.json';
  const recipientList = (process.env.EMAIL_RECIPIENTS || '').split(',').filter(Boolean);

  if (recipientList.length === 0) {
    console.log('Set EMAIL_RECIPIENTS in .env (comma-separated)');
    process.exit(1);
  }

  const summary = parsePlaywrightResults(resultsFile);
  sendTestReport(recipientList, summary).then(() => console.log('Done!'));
}
