import { test, expect } from '@playwright/test';

async function login(request: any, username = 'operator', password = 'operator123'): Promise<string> { const response = await request.post('/api/login', { data: { username, password } }); expect(response.status()).toBe(200); return (await response.json()).token; }

test.describe('Fulfillment Console complex challenge', () => {
  test('API authenticates, searches, creates orders, and meets SLA @api @smoke', async ({ request }) => { const token = await login(request); const started = Date.now(); const inventory = await request.get('/api/items?q=scanner', { headers: { authorization: `Bearer ${token}` } }); expect(Date.now() - started).toBeLessThan(500); expect((await inventory.json()).items[0].sku).toBe('FUL-001'); const order = await request.post('/api/orders', { headers: { authorization: `Bearer ${token}` }, data: { itemId: 1, quantity: 2 } }); expect(order.status()).toBe(201); expect((await order.json()).id).toMatch(/^ORD-/); });
  test('API rejects invalid login, stock overflow, and unauthorized restock @api', async ({ request }) => { expect((await request.post('/api/login', { data: { username: 'operator', password: 'wrong' } })).status()).toBe(401); const token = await login(request); expect((await request.post('/api/restock', { headers: { authorization: `Bearer ${token}` }, data: { itemId: 1, quantity: 5 } })).status()).toBe(403); expect((await request.post('/api/orders', { headers: { authorization: `Bearer ${token}` }, data: { itemId: 1, quantity: 999 } })).status()).toBe(409); });
  test('supervisor can use restock endpoint @api', async ({ request }) => { const token = await login(request, 'supervisor', 'supervisor123'); expect((await request.post('/api/restock', { headers: { authorization: `Bearer ${token}` }, data: { itemId: 1, quantity: 3 } })).status()).toBe(200); });
  test('UI preserves login, searches, and creates an order @ui @smoke', async ({ page }) => { await page.goto('/'); await page.getByRole('button', { name: 'Sign in' }).click(); await expect(page.getByRole('status')).toHaveText('Signed in as operator'); await page.getByLabel('Search inventory').fill('scanner'); await expect(page.getByText(/FUL-001 - Barcode Scanner/)).toBeVisible(); await page.getByLabel('Quantity').fill('1'); await page.getByRole('button', { name: 'Create order' }).click(); await expect(page.getByRole('alert')).toContainText('created'); });
  test('UI rejects invalid login on mobile layout @ui', async ({ page }) => { await page.goto('/'); await page.getByLabel('Password').fill('bad-password'); await page.getByRole('button', { name: 'Sign in' }).click(); await expect(page.locator('[role="alert"]')).toHaveText('invalid credentials'); await expect(page.getByRole('main')).toBeVisible(); });
});
